---
cache_apps:
  - spotify
  - thunderbird
  - firefox
  - discord
  - shotwell
  - gnome
  - plex
cache_extensions:
  - .so
  - .conf
  - .config
  - .xpi
  - .0
  - .1
path_stubs:
  - /usr/bin/
  - /usr/lib/
  - /usr/share/
  - /snap/
max_file_size: 100mb
...
