---

## Below are some config options for accelaunch and brief descriptions
## as to their meaning and use.

## Drop the caches when the service is stopped.  Mostly for debugging.
## This does nothing but decrease performance, recommended setting is
## always False unless you know what you are doing.
drop_caches_on_stop: False

## The root apps that the code looks for.
cache_apps:
  - spotify
  - thunderbird
  - firefox
  - discord
  - shotwell
  - vlc

## These are the file extensions that accelaunch looks for at the
## end of the paths (on the filename), and matching ones are pushed
## to disk cache (memory).  Files without an extension are
## automatically added.
cache_extensions:
  - .so
  - .xpi
  - .0
  - .1
  - .conf
  - .config
  - .py

## Paths where our accelaunch attempts to find files in.
path_stubs:
  - /usr/bin/
  - /usr/lib/
  - /usr/share/
  - /snap/
  - /opt/

## Paths to files that should always be cached.
extra_files:
  - /usr/bin/snap
  - /usr/bin/gnome-terminal

## The log file path if left blank, no log
log_file: /var/log/accelaunch.log

## If your system is low on memory, you may want to decrease this to
# mitigate large files that may never be accessed from being added
# to memory.
max_file_size: 20mb

## cache drop level (1 to 3)
## The level passed to /proc/sys/vm/drop_caches on stop or restart
drop_caches_level: 1

...
