---

## Below are some config options for accelaunch and brief descriptions
## as to their meaning and use.

## Drop the caches when the service is stopped.  Mostly for debugging.
## This does nothing but decrease performance, recommended setting is
## always False unless you know what you are doing.
drop_caches_on_stop: False

## The root apps that the code looks for.
cache_apps:
  - spotify
  - thunderbird
  - firefox
  - discord
  - shotwell
  - gnome
  - plex

## These are the file extensions that accelaunch looks for at the
## end of the paths (on the filename), and matching ones are pushed
## to disk cache (memory).
cache_extensions:
  - .so
  - .conf
  - .config
  - .xpi
  - .0
  - .1

## Paths where our accelaunch attempts to find files in.
path_stubs:
  - /usr/bin/
  - /usr/lib/
  - /usr/share/
  - /snap/

## If your system is low on memory, you may want to decrease this to
# mitigate large files that may never be accessed from being added
# to memory.
max_file_size: 100mb
...
